export const DEFAULT_EMOJIS: CustomEmojiConfig[] = [
  {
    emoji: '🎨',
    name: ':art:',
    alias: 'art',
    description: 'Improve structure / format of the code.',
  },
  {
    emoji: '⚡️',
    name: ':zap:',
    alias: 'zap',
    description: 'Improve performance.',
  },
  {
    emoji: '🔥',
    name: ':fire:',
    alias: 'fire',
    description: 'Remove code or files.',
  },
  {
    emoji: '🐛',
    name: ':bug:',
    alias: 'bug',
    description: 'Fix a bug.',
  },
  {
    emoji: '🚑️',
    name: ':ambulance:',
    alias: 'ambulance',
    description: 'Critical hotfix.',
  },
  {
    emoji: '✨',
    name: ':sparkles:',
    alias: 'sparkles',
    description: 'Introduce new features.',
  },
  {
    emoji: '📝',
    name: ':memo:',
    alias: 'memo',
    description: 'Add or update documentation.',
  },
  {
    emoji: '🚀',
    name: ':rocket:',
    alias: 'rocket',
    description: 'Deploy stuff.',
  },
  {
    emoji: '💄',
    name: ':lipstick:',
    alias: 'lipstick',
    description: 'Add or update the UI and style files.',
  },
  {
    emoji: '🎉',
    name: ':tada:',
    alias: 'tada',
    description: 'Begin a project.',
  },
  {
    emoji: '✅',
    name: ':white_check_mark:',
    alias: 'white-check-mark',
    description: 'Add, update, or pass tests.',
  },
  {
    emoji: '🔒️',
    name: ':lock:',
    alias: 'lock',
    description: 'Fix security issues.',
  },
  {
    emoji: '🔐',
    name: ':closed_lock_with_key:',
    alias: 'closed-lock-with-key',
    description: 'Add or update secrets.',
  },
  {
    emoji: '🔖',
    name: ':bookmark:',
    alias: 'bookmark',
    description: 'Release / Version tags.',
  },
  {
    emoji: '🚨',
    name: ':rotating_light:',
    alias: 'rotating-light',
    description: 'Fix compiler / linter warnings.',
  },
  {
    emoji: '🚧',
    name: ':construction:',
    alias: 'construction',
    description: 'Work in progress.',
  },
  {
    emoji: '💚',
    name: ':green_heart:',
    alias: 'green-heart',
    description: 'Fix CI Build.',
  },
  {
    emoji: '⬇️',
    name: ':arrow_down:',
    alias: 'arrow-down',
    description: 'Downgrade dependencies.',
  },
  {
    emoji: '⬆️',
    name: ':arrow_up:',
    alias: 'arrow-up',
    description: 'Upgrade dependencies.',
  },
  {
    emoji: '📌',
    name: ':pushpin:',
    alias: 'pushpin',
    description: 'Pin dependencies to specific versions.',
  },
  {
    emoji: '👷',
    name: ':construction_worker:',
    alias: 'construction-worker',
    description: 'Add or update CI build system.',
  },
  {
    emoji: '📈',
    name: ':chart_with_upwards_trend:',
    alias: 'chart-with-upwards-trend',
    description: 'Add or update analytics or track code.',
  },
  {
    emoji: '♻️',
    name: ':recycle:',
    alias: 'recycle',
    description: 'Refactor code.',
  },
  {
    emoji: '➕',
    name: ':heavy_plus_sign:',
    alias: 'heavy-plus-sign',
    description: 'Add a dependency.',
  },
  {
    emoji: '➖',
    name: ':heavy_minus_sign:',
    alias: 'heavy-minus-sign',
    description: 'Remove a dependency.',
  },
  {
    emoji: '🔧',
    name: ':wrench:',
    alias: 'wrench',
    description: 'Add or update configuration files.',
  },
  {
    emoji: '🔨',
    name: ':hammer:',
    alias: 'hammer',
    description: 'Add or update development scripts.',
  },
  {
    emoji: '🌐',
    name: ':globe_with_meridians:',
    alias: 'globe-with-meridians',
    description: 'Internationalization and localization.',
  },
  {
    emoji: '✏️',
    name: ':pencil2:',
    alias: 'pencil2',
    description: 'Fix typos.',
  },
  {
    emoji: '💩',
    name: ':poop:',
    alias: 'poop',
    description: 'Write bad code that needs to be improved.',
  },
  {
    emoji: '⏪️',
    name: ':rewind:',
    alias: 'rewind',
    description: 'Revert changes.',
  },
  {
    emoji: '🔀',
    name: ':twisted_rightwards_arrows:',
    alias: 'twisted-rightwards-arrows',
    description: 'Merge branches.',
  },
  {
    emoji: '📦️',
    name: ':package:',
    alias: 'package',
    description: 'Add or update compiled files or packages.',
  },
  {
    emoji: '👽️',
    name: ':alien:',
    alias: 'alien',
    description: 'Update code due to external API changes.',
  },
  {
    emoji: '🚚',
    name: ':truck:',
    alias: 'truck',
    description: 'Move or rename resources (e.g.: files, paths, routes).',
  },
  {
    emoji: '📄',
    name: ':page_facing_up:',
    alias: 'page-facing-up',
    description: 'Add or update license.',
  },
  {
    emoji: '💥',
    name: ':boom:',
    alias: 'boom',
    description: 'Introduce breaking changes.',
  },
  {
    emoji: '🍱',
    name: ':bento:',
    alias: 'bento',
    description: 'Add or update assets.',
  },
  {
    emoji: '♿️',
    name: ':wheelchair:',
    alias: 'wheelchair',
    description: 'Improve accessibility.',
  },
  {
    emoji: '💡',
    name: ':bulb:',
    alias: 'bulb',
    description: 'Add or update comments in source code.',
  },
  {
    emoji: '🍻',
    name: ':beers:',
    alias: 'beers',
    description: 'Write code drunkenly.',
  },
  {
    emoji: '💬',
    name: ':speech_balloon:',
    alias: 'speech-balloon',
    description: 'Add or update text and literals.',
  },
  {
    emoji: '🗃️',
    name: ':card_file_box:',
    alias: 'card-file-box',
    description: 'Perform database related changes.',
  },
  {
    emoji: '🔊',
    name: ':loud_sound:',
    alias: 'loud-sound',
    description: 'Add or update logs.',
  },
  {
    emoji: '🔇',
    name: ':mute:',
    alias: 'mute',
    description: 'Remove logs.',
  },
  {
    emoji: '👥',
    name: ':busts_in_silhouette:',
    alias: 'busts-in-silhouette',
    description: 'Add or update contributor(s).',
  },
  {
    emoji: '🚸',
    name: ':children_crossing:',
    alias: 'children-crossing',
    description: 'Improve user experience / usability.',
  },
  {
    emoji: '🏗️',
    name: ':building_construction:',
    alias: 'building-construction',
    description: 'Make architectural changes.',
  },
  {
    emoji: '📱',
    name: ':iphone:',
    alias: 'iphone',
    description: 'Work on responsive design.',
  },
  {
    emoji: '🤡',
    name: ':clown_face:',
    alias: 'clown-face',
    description: 'Mock things.',
  },
  {
    emoji: '🥚',
    name: ':egg:',
    alias: 'egg',
    description: 'Add or update an easter egg.',
  },
  {
    emoji: '🙈',
    name: ':see_no_evil:',
    alias: 'see-no-evil',
    description: 'Add or update a .gitignore file.',
  },
  {
    emoji: '📸',
    name: ':camera_flash:',
    alias: 'camera-flash',
    description: 'Add or update snapshots.',
  },
  {
    emoji: '⚗️',
    name: ':alembic:',
    alias: 'alembic',
    description: 'Perform experiments.',
  },
  {
    emoji: '🔍️',
    name: ':mag:',
    alias: 'mag',
    description: 'Improve SEO.',
  },
  {
    emoji: '🏷️',
    name: ':label:',
    alias: 'label',
    description: 'Add or update types.',
  },
  {
    emoji: '🌱',
    name: ':seedling:',
    alias: 'seedling',
    description: 'Add or update seed files.',
  },
  {
    emoji: '🚩',
    name: ':triangular_flag_on_post:',
    alias: 'triangular-flag-on-post',
    description: 'Add, update, or remove feature flags.',
  },
  {
    emoji: '🥅',
    name: ':goal_net:',
    alias: 'goal-net',
    description: 'Catch errors.',
  },
  {
    emoji: '💫',
    name: ':dizzy:',
    alias: 'animation',
    description: 'Add or update animations and transitions.',
  },
  {
    emoji: '🗑️',
    name: ':wastebasket:',
    alias: 'wastebasket',
    description: 'Deprecate code that needs to be cleaned up.',
  },
  {
    emoji: '🛂',
    name: ':passport_control:',
    alias: 'passport-control',
    description: 'Work on code related to authorization, roles and permissions.',
  },
  {
    emoji: '🩹',
    name: ':adhesive_bandage:',
    alias: 'adhesive-bandage',
    description: 'Simple fix for a non-critical issue.',
  },
  {
    emoji: '🧐',
    name: ':monocle_face:',
    alias: 'monocle-face',
    description: 'Data exploration/inspection.',
  },
  {
    emoji: '⚰️',
    name: ':coffin:',
    alias: 'coffin',
    description: 'Remove dead code.',
  },
  {
    emoji: '🧪',
    name: ':test_tube:',
    alias: 'test-tube',
    description: 'Add a failing test.',
  },
  {
    emoji: '👔',
    name: ':necktie:',
    alias: 'necktie',
    description: 'Add or update business logic.',
  },
  {
    emoji: '🩺',
    name: ':stethoscope:',
    alias: 'stethoscope',
    description: 'Add or update healthcheck.',
  },
  {
    emoji: '🧱',
    name: ':bricks:',
    alias: 'bricks',
    description: 'Infrastructure related changes.',
  },
  {
    emoji: '🧑‍💻',
    name: ':technologist:',
    alias: 'technologist',
    description: 'Improve developer experience.',
  },
  {
    emoji: '💸',
    name: ':money_with_wings:',
    alias: 'money-with-wings',
    description: 'Add sponsorships or money related infrastructure.',
  },
  {
    emoji: '🧵',
    name: ':thread:',
    alias: 'thread',
    description: 'Add or update code related to multithreading or concurrency.',
  },
  {
    emoji: '🦺',
    name: ':safety_vest:',
    alias: 'safety-vest',
    description: 'Add or update code related to validation.',
  },
];
