name: 🐛 Bug report
description: Report bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: A clear description the bug. If you want to contribute to fix this issue, tell us in the description.
      placeholder: |
        Describe the bug
        If applicable, add screenshots or error messages.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is **required**, otherwise the issue might be closed without further notice.
      placeholder: |
        e.g.
        - Bug-triggering page URL
        - Clear description of the steps to reproduce the bug
        - Environment where the bug occurs (operating system, browser version, etc.)
        - If necessary, data or code snippets required for reproduction
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --browsers`
      render: Shell
      placeholder: | 
        Paste the output of `npx envinfo --system --binaries --browsers`
        Or directly fill in the following items:
        - Operating System: [e.g. Windows 10]
        - Browser: [e.g. Chrome 90.0.4430.212]
        - Other Environment Info: [e.g. Node version, npm version, pnpm version]
    validations:
      required: true