name: Publish NPM

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          npm install -g pnpm
          pnpm install
          pnpm test

  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
      
      - name: Publish package to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
          npm publish